[package]
name = "fs_service"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fs_service"
path = "src/main.rs"
test = false
bench = false

[dependencies]
std = { path = "../../lib" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true

