[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
swiftlib = { path = "../../user" }

[features]
default = ["run_tests"]
run_tests = []

[profile.release]
panic = "abort"
lto = true

[profile.dev]
panic = "abort"
