[build]
target = "../../x86_64-swiftcore.json"

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-swiftcore]
rustflags = [
    "-C", "link-arg=-nostdlib",
    "-C", "panic=abort",
]
