[build]
target = "../../x86_64-swiftcore.json"

[target.x86_64-swiftcore]
rustflags = [
    "-C", "link-arg=-nostdlib",
    "--cfg", "libc_priv_libc",
    "--cfg", "libc_core_cstd",
    "--cfg", "target_os=\"freebsd\"", 
]